### ISSUE TITLE
Job list done - Who completed the job?

### ISSUE THREAD

**Issue by LimeeFox** [StealWonders/EpicJobs#1]
Hello dear developer!

I recently issued the command `/jobs list done` and there were two jobs awaiting for my `/job complete`, however I wanted to know who completed this job before approving it. Could you add an indication of the player's name who finished the job to the job info?

Thank you!

**Comment by LimeeFox** [comment]
Same for every job that's taken `/jobs list status taken` and other status categories

**Comment by StealWonders** [comment]
Was added in release v1.1
