### ISSUE TITLE
Shift+ Left Click for Job Complete is slightly bugged

### ISSUE THREAD

**Issue by LimeeFox** [StealWonders/EpicJobs#10]
When I use the keybind to mark a job as complete, it marks it as complete but the job icon disappears from the menu only after closing and reopening it.

**Comment by StealWonders** [comment]
Works as intended and cannot be changed without major technical changes. The entire menu would have to be re-drawn as all the other items would have to move up one slot and forward/backward buttons would also have to be taken into account.
Closing issue.
