### ISSUE TITLE
Rename some categories

### ISSUE THREAD

**Issue by Tobberz** [StealWonders/EpicJobs#7]
At the moment, most of the job categories are a ok, but I feel some should be tweaked or maybe added.

There should be a distinction between "Interior Structure" - i.e; walls, room planning, etc etc; and "Interior Decoration" - i.e:... decoration.

Currently we use "INTERIOR" to mean Interior Structure and "DECORATION" to mean **either** Interior Decoration _or_ Exterior Decoration, which isn't perfect.

**Conclusion**
You should split the INTERIOR label into INT_STRUCTURE and INT_DECOR, imo.

**Comment by StealWonders** [comment]
Seems redundant to me as most interior builders can do both. Laying out the interior structure can either be done when building the house itself or when the interior builder starts his work, allowing him more creative freedom. I don't think an interior structure category is needed to plan out tiny walls and doorways.

**Comment by Tobberz** [comment]
Fair enough, I'll try and change the way EQ builds instead ;)
